DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS participant;

CREATE TABLE room (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE participant (
  room_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES room (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
);
